name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json
      - name: Install
        run: npm ci
      - name: Lint
        run: npx eslint --no-error-on-unmatched-pattern . || true
      - name: Build
        run: npm run build --if-present

  backend-smoke:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Backend/package-lock.json
      - name: Install
        run: npm ci
      - name: Env
        run: |
          echo "PORT=5000" >> .env
          echo "FRONTEND_URL=http://localhost:3000" >> .env
          echo "MONGODB_URI=mongodb://127.0.0.1:27017/dummy" >> .env
          echo "JWT_SECRET=dummy" >> .env
      - name: Start and health-check
        run: |
          node server.js &
          sleep 3
          curl -f http://localhost:5000/health
